repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files # Prevent giant files from being committed
      - id: check-case-conflict # Checks for files that conflict in case-insensitive filesystems
      - id: check-json # Attempts to load all json files to verify syntax
      - id: check-merge-conflict # Check for files that contain merge conflict strings
      - id: check-symlinks # Checks for symlinks which do not point to anything
      - id: check-xml # Attempts to load all xml files to verify syntax
      - id: check-yaml # Attempts to load all yaml files to verify syntax
      - id: debug-statements # Check for debugger imports and breakpoint() calls in python code
      - id: end-of-file-fixer # Makes sure files end in a newline and only a newline
      - id: no-commit-to-branch
        # Protect 'main' branch from direct commits and also ensure branch names are lowercase to
        # avoid clashes on case-insensitive filesystems
        args: ['-p', '.*[^0-9a-z-_/.=].*']
      - id: trailing-whitespace # Trims trailing whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff # Run `ruff` linter
        name: Check 'ruff linter' passes
        stages: [pre-commit, pre-push]
        args: [--fix, --exit-non-zero-on-fix]

      - id: ruff-format # Run `ruff` formatter
        name: Check 'ruff format' passes

  - repo: https://github.com/shssoichiro/oxipng
    rev: v9.1.5
    hooks:
      - id: oxipng

ci:
  autofix_prs: false
