site_name: Django-subatomic docs
repo_name: kraken-tech/django-subatomic
repo_url: https://github.com/kraken-tech/django-subatomic
theme:
  name: material
extra:
  version:
    provider: mike
    alias: true
    default:
      - latest
plugins:
  - search
  - mike
