site_name: Django-subatomic docs
repo_name: kraken-tech/django-subatomic
repo_url: https://github.com/kraken-tech/django-subatomic
theme:
  name: material
  logo: static/img/logo.png
  features:
    - navigation.indexes
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: kraken
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra_css:
  - static/css/theme.css
extra:
  version:
    provider: mike
    alias: true
    default:
      - latest
markdown_extensions:
  - tables
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            separate_signature: true
            show_signature_annotations: true
            show_signature_type_parameters: true
  - api-autonav:
      modules: ['src/django_subatomic']
  - search
  - mike
