
[lint]
select = ["ALL"]
ignore = [
    "COM812", "E501", "ISC001",  # Conflict with formatter
    "CPY001", # We do not include copyright notices in individual files
    "D1", # Requires docstrings where we don't need them
    "D200", "D212", # Conflict with Kraken docstring conventions
    "N818", # Requires Hungarian notation for exceptions
    "PT007",  # Unecessarily fussy
    "RET505", # Disallows some explicit control flow that we prefer
]

[lint.per-file-ignores]
# Allow unused imports in `__init__.py` files as these are convenience imports.
"__init__.py" = [ "F401" ]
"tests/*.py" = [  # pragma: alphabetize
    "PLR2004",  # allow comparison to values
    "S101",  # allow `assert` for test assertions
    "SIM117",  # allow nested `with` statements for clarity
]

"tests/**" = [
    "ANN", # Type hints
    "FBT001",  # Boolean-typed positional argument in function definition
]

[lint.isort]
lines-after-imports = 2
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "project",
    "local-folder",
]

[lint.isort.sections]
"project" = [
    "django_subatomic",
    "tests",
]

[lint.pydocstyle]
convention = "google"
