[tox]
requires =
    tox>=4

env_list =
    py3{12,13,14}-django{42,51,52,60}-{mariadb,postgres,sqlite}
    coverage
    mypy

[testenv]
# Install wheels instead of source distributions for faster execution.
package = wheel

# Share the build environment between tox environments.
wheel_build_env = .pkg

setenv =
    mariadb: DEFAULT_DATABASE_URL={env:DEFAULT_MARIADB_URL:mysql:///subatomic/}
    mariadb: OTHER_DATABASE_URL={env:OTHER_MARIADB_URL:mysql:///subatomic_other/}
    postgres: DEFAULT_DATABASE_URL={env:DEFAULT_POSTGRES_URL:postgres:///subatomic}
    postgres: OTHER_DATABASE_URL={env:OTHER_POSTGRES_URL:postgres:///subatomic_other}
    sqlite: DEFAULT_DATABASE_URL={env:DEFAULT_SQLITE_URL:sqlite:///test-default-db.sqlite}
    sqlite: OTHER_DATABASE_URL={env:OTHER_SQLITE_URL:sqlite:///test-other-db.sqlite}

dependency_groups =
    coverage
    python_tests

deps =
    django42: django~=4.2.0
    django51: django~=5.1.0
    django52: django~=5.2.0
    django60: django~=6.0.0
    mariadb: mysqlclient

commands =
    coverage run --parallel -m pytest {posargs}

[testenv:coverage]
depends =
    py3{12,13,14}-django{42,51,52,60}-postgres

dependency_groups =
    coverage

commands =
    coverage combine
    coverage report

[testenv:mypy]
dependency_groups =
    mypy

commands =
    python -m mypy .

set_env =
    TERM=xterm-256color
