name: build main branch docs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version-file: '.github/workflows/.python-version'
      - name: Install Dependencies
        run: |
          pip install --group docs .
      - name: Configure git
        run: |
          git config --global user.name "GitHub docs action"
          git config --global user.email "django-subatomic+docs@example.com"
      - name: Build Docs Site
        run: |
          mike deploy --push --update-aliases dev
